---
- name: Instalando Docker AWS EC2
  hosts: docker-ec2
  become: true
  gather_facts: no

  tasks:
    - name: Atualizando o sistema operacional
      apt:
        name: '*'
        state: latest

    - name: Instalando pacotes necessários
      apt:
        pkg: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - openjdk-8-jre
        state: latest
        update_cache: yes
    
    - name: Adicionando Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionando Repositorio Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Atualizando o apt e instalando o docker-ce
      apt: 
        pkg: 
        - docker-ce
        - python3-pip
        update_cache: yes
        state: latest
    
    - name: Instalando modulo docker python
      pip:
        name: docker

    - name: Adicionando Key Jenkins
      apt_key: 
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key 
        state: present

    - name: Adicionando repositorio do Jenkins
      apt_repository: 
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Instalando o Jenkins
      apt: 
        name: jenkins
        update_cache: yes

    - name: Iniciando o serviço do Jenkins
      service: 
        name: jenkins
        state: started

    - name: Adicionando usuario jenkins ao grupo Docker
      user: 
        name: jenkins
        groups: docker
        append: yes
